language: ruby

rvm:
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - ruby-head

addons:
  chrome: stable

gemfile:
  - gemfiles/csv_15.0.gemfile
  - gemfiles/csv_16.0.gemfile

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

before_install:
  - nvm install 12
  - node -v
  - npm i -g yarn@^1.21.1
  - yarn
  - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

script: bundle exec rake test:all
